apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: rs-news-dev-ns

resources:
- config.yaml
- gateway.yaml
- ./efs/pv-claim.yaml
- ../../loader
- ../../filter
- ../../portrait
- ../../rank
- ../../recall
- ../../redis
- ../../event
- ../../retrieve
- ../../demo
- ui
- ../../personalize

# all with following *kustomization*
images:
- name: rs/demo
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/demo
  newTag: 9f4237654106e79a36e5f9a46e362ff52102a9cb
- name: rs/event
  newName: public.ecr.aws/t8u1z3c8/rs/event
  newTag: latest
- name: rs/filter
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter
  newTag: 5de3b00d4d69969cd4a25804577b2e5bb59aa979
- name: rs/filter-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter-plugin
  newTag: news-5de3b00d4d69969cd4a25804577b2e5bb59aa979
- name: rs/loader
  newName: public.ecr.aws/t8u1z3c8/rs/loader
  newTag: latest
- name: rs/personalize
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/personalize
  newTag: 9f4237654106e79a36e5f9a46e362ff52102a9cb
- name: rs/portrait
  newName: public.ecr.aws/t8u1z3c8/rs/portrait
  newTag: latest
- name: rs/portrait-plugin
  newName: public.ecr.aws/t8u1z3c8/rs/portrait-plugin
  newTag: latest
- name: rs/rank
  newName: public.ecr.aws/t8u1z3c8/rs/rank
  newTag: latest
- name: rs/rank-plugin
  newName: public.ecr.aws/t8u1z3c8/rs/rank-plugin
  newTag: latest
- name: rs/recall
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall
  newTag: d6519af531d6c95df773bd123583edc7511ce44d
- name: rs/recall-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall-plugin
  newTag: news-d6519af531d6c95df773bd123583edc7511ce44d
- name: rs/retrieve
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/retrieve
  newTag: b12a28de6431d2bea29f7cf6e6b4c91953716b23
- name: rs/ui
  newName: public.ecr.aws/t8u1z3c8/rs/ui
  newTag: latest



vars:
- fieldref:
    fieldPath: data.redis_host
  name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.redis_port
  name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_host
  name: MESSGE_BROKER_REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_port
  name: MESSGE_BROKER_REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.aws_region
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_bucket
  name: S3_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_prefix
  name: S3_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_bucket
  name: CLICK_RECORD_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_file_path
  name: CLICK_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.user_record_file_path
  name: USER_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.local_data_folder
  name: LOCAL_DATA_FOLDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
