apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcr-rs-workshop-cluster
  region: ap-northeast-1
  version: "1.19"

nodeGroups:
  - name: rs-cpu-ng
    labels: { role: rs-cpu-ng }
    instanceType: r5.2xlarge
    minSize: 2
    maxSize: 4
    volumeSize: 80
    ssh:
      allow: true
      enableSsm: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess        
      withAddonPolicies:
        imageBuilder: true
        externalDNS: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
        appMesh: true
        xRay: true
        autoScaler: true
        albIngress: true
        cloudWatch: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/gcr-rs-workshop-cluster: "owned"