apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-movie-dev
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-movie-dev
  csi:
    driver: efs.csi.aws.com
    # volumeHandle: fs-b2ab7ef2
